"""In-container runner (T-006-05). Generated by tios.adapters.hummingbot.lane; runs
inside the pinned hummingbot/hummingbot:version-2.15.0 image, conda env "hummingbot".

Injects frozen candles directly into BacktestingDataProvider.candles_feeds (no live
fetch, no network dependency) and drives BacktestingEngineBase.run_backtesting()
with a signal-based DirectionalTradingController subclass whose entry/exit logic
mirrors the canonical B1-B4 specs bar-for-bar (same pandas formulas as the
Freqtrade lane's populate_indicators/populate_entry_trend/populate_exit_trend).

CapabilityGap (documented, not silent): DirectionalTradingControllerBase's native
exit path is triple-barrier (stop-loss/take-profit/time-limit) only; canonical
B1-B4 exit on a signal flip instead. We disable the triple barrier (stop_loss=
take_profit=time_limit=None) and add exit-signal handling via an overridden
stop_actions_proposal — a supported extension point, not a monkeypatch of engine
internals.
"""

from __future__ import annotations

import argparse
import asyncio
import json
from decimal import Decimal
from typing import Any

import pandas as pd
from hummingbot.core.data_type.common import PositionMode
from hummingbot.strategy_v2.backtesting.backtesting_engine_base import BacktestingEngineBase
from hummingbot.strategy_v2.controllers.directional_trading_controller_base import (
    DirectionalTradingControllerBase,
    DirectionalTradingControllerConfigBase,
)
from hummingbot.strategy_v2.models.executor_actions import ExecutorAction, StopExecutorAction

CONNECTOR = "binance"
INTERVAL = "5m"


def compute_signals(baseline: str, df: pd.DataFrame) -> pd.DataFrame:
    """Same formulas as src/tios/adapters/freqtrade/lane.py STRATEGY_SOURCES; entry=1
    means "open long if flat", exit=1 means "close if in a long"."""
    out = df[["timestamp"]].copy()
    close, high = df["close"], df["high"]
    if baseline == "B1":
        out["entry"] = 0
        out.loc[out.index[0], "entry"] = 1
        out["exit"] = 0
    elif baseline == "B2":
        sma_fast = close.rolling(3).mean()
        sma_slow = close.rolling(5).mean()
        out["entry"] = (sma_fast > sma_slow).astype(int)
        out["exit"] = (sma_fast < sma_slow).astype(int)
    elif baseline == "B3":
        middle = close.rolling(3).mean()
        std = close.rolling(3).std(ddof=0)
        lower = middle - 1 * std
        out["entry"] = (close < lower).astype(int)
        out["exit"] = (close >= middle).astype(int)
    elif baseline == "B4":
        hh_prev5 = high.rolling(5).max().shift(1)
        sma3 = close.rolling(3).mean()
        out["entry"] = (close > hh_prev5).astype(int)
        out["exit"] = (close < sma3).astype(int)
    else:
        raise ValueError(baseline)
    out[["entry", "exit"]] = out[["entry", "exit"]].fillna(0).astype(int)
    return out


class BaselineControllerConfig(DirectionalTradingControllerConfigBase):
    controller_name: str = "baseline"
    baseline: str = "B1"

    def get_controller_class(self):
        return BaselineController


class BaselineController(DirectionalTradingControllerBase):
    def __init__(self, config: BaselineControllerConfig, *args, **kwargs):
        super().__init__(config, *args, **kwargs)
        self._features_cache: pd.DataFrame | None = None

    async def update_processed_data(self) -> None:
        if self._features_cache is None:
            df = self.market_data_provider.get_candles_df(
                connector_name=self.config.connector_name,
                trading_pair=self.config.trading_pair,
                interval=INTERVAL,
            ).copy()
            sig = compute_signals(self.config.baseline, df)
            features = df[["timestamp"]].merge(sig, on="timestamp")
            self._features_cache = features.rename(
                columns={"entry": "signal", "exit": "exit_signal"}
            )
        self.processed_data = {"signal": 0, "exit_signal": 0, "features": self._features_cache}

    def stop_actions_proposal(self) -> list[ExecutorAction]:
        actions: list[ExecutorAction] = []
        if self.processed_data.get("exit_signal", 0):
            for executor in self.filter_executors(
                executors=self.executors_info, filter_func=lambda x: x.is_active
            ):
                actions.append(
                    StopExecutorAction(controller_id=self.config.id, executor_id=executor.id)
                )
        return actions


def build_config(baseline: str, trading_pair: str) -> BaselineControllerConfig:
    return BaselineControllerConfig(
        id=f"baseline-{baseline}-{trading_pair}",
        controller_name="baseline",
        baseline=baseline,
        connector_name=CONNECTOR,
        trading_pair=trading_pair,
        total_amount_quote=Decimal("1000"),
        max_executors_per_side=1,
        cooldown_time=1,
        leverage=1,
        position_mode=PositionMode.ONEWAY,
        # ponytail: the framework's triple-barrier fields aren't robust to None
        # (NaN propagates into pydantic-validated ExecutorInfo); use effectively
        # unreachable finite bounds so only the canonical signal-based exit fires.
        stop_loss=Decimal("100"),
        take_profit=Decimal("100"),
        time_limit=200 * 365 * 24 * 3600,
    )


def load_candles(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    df = df[["timestamp", "open", "high", "low", "close", "volume"]].sort_values("timestamp")
    # ponytail: pandas 3.x's DataFrame.set_index silently collapses an evenly-spaced
    # int64 column into a RangeIndex; BacktestingEngineBase.prepare_market_data() calls
    # set_index("timestamp") on our data internally (post merge_asof) and hits the same
    # collapse, then hummingbot's bare `df[:tl_timestamp]` slice fails because
    # tl_timestamp is a float (iterrows() upcasts a mixed int/float row to float64) —
    # RangeIndex rejects float slice bounds even when its values are integral. Keeping
    # "timestamp" float64 end-to-end prevents the RangeIndex collapse, so both the index
    # and the slice bound are float and the slice works. Upgrade path: drop this once
    # hummingbot casts timestamp to a fixed dtype before its internal set_index call.
    df["timestamp"] = df["timestamp"].astype(float)
    df = df.set_index("timestamp", drop=False)
    df.index.name = "epoch_seconds"
    return df


async def run_one(
    baseline: str, trading_pair: str, csv_path: str, start: int, end: int, trade_cost: float
) -> dict[str, Any]:
    engine = BacktestingEngineBase()
    key = f"{CONNECTOR}_{trading_pair}_{INTERVAL}"
    engine.backtesting_data_provider.candles_feeds[key] = load_candles(csv_path)
    config = build_config(baseline, trading_pair)
    result = await engine.run_backtesting(
        config, start, end, backtesting_resolution=INTERVAL, trade_cost=trade_cost
    )

    executors = [json.loads(json.dumps(ei.to_dict(), default=str)) for ei in result["executors"]]
    return {
        "engine": "hummingbot",
        "baseline": baseline,
        "trading_pair": trading_pair,
        "trade_cost": trade_cost,
        "start": start,
        "end": end,
        "results": {
            k: (str(v) if isinstance(v, Decimal) else v) for k, v in result["results"].items()
        },
        "executors": executors,
        "pnl_timeseries": result["pnl_timeseries"],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline", required=True)
    parser.add_argument("--trading-pair", required=True)
    parser.add_argument("--csv", required=True)
    parser.add_argument("--start", type=int, required=True)
    parser.add_argument("--end", type=int, required=True)
    parser.add_argument("--trade-cost", type=float, required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    out = asyncio.run(
        run_one(args.baseline, args.trading_pair, args.csv, args.start, args.end, args.trade_cost)
    )
    with open(args.out, "w") as f:
        json.dump(out, f, indent=2)
    print(f"OK wrote {args.out}")


if __name__ == "__main__":
    main()
